#!/usr/bin/env bash
# Claude Code profile for the provider-neutral interactive tmux runner.

: "${MODEL:?MODEL must be set by the calling runner script}"

AGENT_PROVIDER="claude"
AGENT_BIN="${CLAUDE_BIN:-claude}"
AGENT_READY_REGEX='(\? for shortcuts|bypass(ing)? permissions|❯)'
AGENT_RESUME_FLAG="--resume"
AGENT_FORK_FLAG="--fork-session"
AGENT_UNSET_ENV_VARS=(
  CLAUDE_CODE_OAUTH_TOKEN
  ANTHROPIC_API_KEY
  ANTHROPIC_AUTH_TOKEN
)
AGENT_ARGS=(
  --model "$MODEL"
  --dangerously-skip-permissions
)

INTERACTIVE_TMUX_TIMEOUT_SECONDS="${INTERACTIVE_TMUX_TIMEOUT_SECONDS:-${CLAUDE_TMUX_TIMEOUT_SECONDS:-21600}}"
INTERACTIVE_TMUX_STARTUP_TIMEOUT_SECONDS="${INTERACTIVE_TMUX_STARTUP_TIMEOUT_SECONDS:-${CLAUDE_TMUX_STARTUP_TIMEOUT_SECONDS:-45}}"
INTERACTIVE_TMUX_POLL_SECONDS="${INTERACTIVE_TMUX_POLL_SECONDS:-${CLAUDE_TMUX_POLL_SECONDS:-1}}"
INTERACTIVE_TMUX_KEEP_SESSION_ON_DONE="${INTERACTIVE_TMUX_KEEP_SESSION_ON_DONE:-${CLAUDE_TMUX_KEEP_SESSION_ON_DONE:-true}}"

source "$(dirname "${BASH_SOURCE[0]}")/_interactive_tmux.sh"
